spring:
  application:
    name: java-core-homework
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5435/java_core_homework}
    username: ${DB_USERNAME:homework}
    password: ${DB_PASSWORD:secret}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
  sql:
    init:
      mode: never
server:
  port: 8090
