create table user_accounts (
    id bigint generated by default as identity primary key,
    username varchar(255) not null,
    display_name varchar(255) not null,
    created_at timestamp(6) with time zone not null,
    constraint uk_user_accounts_username unique (username)
);
