create table questions (
    id bigint generated by default as identity primary key,
    topic varchar(255) not null,
    difficulty varchar(255) not null,
    type varchar(255) not null,
    question_text varchar(1000) not null,
    option_a varchar(500),
    option_b varchar(500),
    option_c varchar(500),
    correct_answer varchar(255) not null,
    explanation varchar(1000) not null
);

create index idx_questions_topic_difficulty on questions (topic, difficulty);
