create table quiz_attempts (
    id bigint generated by default as identity primary key,
    user_account_id bigint not null,
    question_id bigint not null,
    given_answer varchar(255) not null,
    correct boolean not null,
    answered_at timestamp(6) with time zone not null,
    constraint fk_quiz_attempts_user_account
        foreign key (user_account_id) references user_accounts (id),
    constraint fk_quiz_attempts_question
        foreign key (question_id) references questions (id)
);

create index idx_quiz_attempts_user_account on quiz_attempts (user_account_id);
create index idx_quiz_attempts_question on quiz_attempts (question_id);
